#!/bin/sh
set -ex

apt-get -y install git python-software-properties
add-apt-repository ppa:webupd8team/java
add-apt-repository ppa:chris-lea/node.js 
apt-get update

echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
apt-get -y install oracle-java8-installer
update-alternatives --display java

echo "JAVA_HOME=/usr/lib/jvm/java-8-oracle" >> /etc/environment

cp lein /usr/local/bin
chmod 755 /usr/local/bin/lein

echo "export LEIN_ROOT=1" >> /etc/environment
export LEIN_ROOT=1
/usr/local/bin/lein

apt-get -y install nodejs
npm --version
npm install -g bower

apt-get clean
rm -rf /build
rm -rf /tmp/* /var/tmp/*
rm -rf /var/lib/apt/lists/*
rm -f /etc/dpkg/dpkg.cfg.d/02apt-speedup
